### ISSUE TITLE
change theme of UI 

### ISSUE THREAD

**Issue by Azhar221** [Azhar221/TaazaNews#2]

**Comment by Vikas3100** [comment]
please Assign me this issue

**Comment by Azhar221** [comment]
<img width="1511" alt="Screenshot 2024-10-07 at 10 31 35 PM" src="https://github.com/user-attachments/assets/8a606cda-1d95-4e98-b99c-da842174de88">

need to improve the UI by fixing the margins and padding, and also make the colors look better.
